### ISSUE TITLE
免责申明表述有误

### ISSUE THREAD

**Issue by zhyjc6** [iamshuaidi/CS-Book#11]
> 书籍全部来源于网络其他人的整理，我这里只是收集整理了他们的链接，如有侵权，马上联系我，我立马删除对应链接。

真的只是收集整理了他人的链接嘛？明明是自己根据他人链接获取了资源，放的是自己的链接啊！楼主这里表述有误，也许可以改一下 :）

**Comment by gaoxin29** [comment]
????????????????




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhyjc6"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 下午3:10
收件人:&nbsp;"iamshuaidi/CS-Book"<CS-Book@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[iamshuaidi/CS-Book] 免责申明表述有误 (#11)





  
书籍全部来源于网络其他人的整理，我这里只是收集整理了他们的链接，如有侵权，马上联系我，我&gt; 立马删除对应链接。
 真的只是收集整理了他人的链接嘛？明明是自己根据他人链接获取了资源，放的是自己的链接啊！楼主这里表述有误，也许可以改一下 :）
