### ISSUE TITLE
Java编程思想，下下来根本不是,原以为这是是个不错的项目，呵呵

### ISSUE THREAD

**Issue by FrankAblert** [iamshuaidi/CS-Book#2]

**Comment by 22dimensions** [comment]
大部分还是可以的



---原始邮件---
发件人: "FrankAblert"<notifications@github.com&gt;
发送时间: 2019年12月30日(周一) 中午11:25
收件人: "iamshuaidi/CS-Book"<CS-Book@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [iamshuaidi/CS-Book] Java编程思想，下下来根本不是,原以为这是是个不错的项目，呵呵 (#2)



Closed #2.

**Comment by Apollo-12** [comment]
怎么了
