### ISSUE TITLE
是否能够做一个集合包？

### ISSUE THREAD

**Issue by Charles276** [iamshuaidi/CS-Book#4]
老哥好，这个资源整合的确不错，我买书也是一般先看电子版，然后再买实体书（没办法，专业书真的贵）但一个一个保存似乎有点麻烦。不知道老哥能麻烦一下弄一个整合包版本吗？（如果有批量保存的方式，也麻烦指点一下）

**Comment by tartail** [comment]
看着哪个有价值再保存，不要做松鼠。
